---
- name: Install NCPA and Register Host and Services
  hosts: ubuntu
  remote_user: root

  vars_files:
    - 'secrets.yml'
  vars:
    xi_ip: '10.0.0.183'

  roles:
    - role: ncpa_install_linux
    - role: register_with_xi
    - role: xi_apply_config
